# Generated by Django 5.2.6 on 2025-09-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='user',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('superuser', 'Superusuário'), ('admin', 'Administrador'), ('coordenador', 'Coordenador'), ('professor', 'Professor'), ('aluno', 'Aluno'), ('pai', 'Pai/Responsável')], default='professor', max_length=20),
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('superuser', 'Superusuário'), ('admin', 'Administrador'), ('coordenador', 'Coordenador'), ('professor', 'Professor'), ('aluno', 'Aluno'), ('pai', 'Pai/Responsável')], max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('permissoes', models.ManyToManyField(blank=True, related_name='tipos_usuario', to='auth.permission', verbose_name='permissoes')),
            ],
            options={
                'verbose_name': 'Tipo de Usuário',
                'verbose_name_plural': 'Tipos de Usuário',
            },
        ),
    ]
