# Generated by Django 5.2.6 on 2025-09-20 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_options_user_ativo_user_data_nascimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='data_nascimento',
        ),
    ]
