# Generated by Django 5.2.1 on 2025-09-22 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_dias_ordem'),
        ('login', '0004_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fk_professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cal.professor', verbose_name='Professor'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
