"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-)dd!$3#$-3uzk76*j=!-$5t5w!=3@&musvy$jz!zj$qa4rfzm6"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['agendamento.pythonanywhere.com']
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'cal',
    'login',
    'rolepermissions',
    'widget_tweaks',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"




# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/



STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# default static files settings for PythonAnywhere.
# see https://help.pythonanywhere.com/pages/DjangoStaticFiles for more info
MEDIA_ROOT = '/home/agendamento/core/media'
MEDIA_URL = '/media/'
STATIC_ROOT = '/home/agendamento/core/static'
STATIC_URL = '/static/'

AUTH_USER_MODEL = 'login.User'
# settings.py


LOGOUT_REDIRECT_URL = '/'


# settings.py

# Configurações de Email (usando console para desenvolvimento)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Para produção, configure um servidor de email real:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'seu-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'sua-senha'

# URL para redirecionamento após reset de senha
LOGIN_REDIRECT_URL = '/calendario/'
LOGIN_URL = '/login/'

# settings.py - Alternativa para debug
# Tempo de expiração do token (em segundos)
PASSWORD_RESET_TIMEOUT = 259200  # 3 dias - padrão do Django

# settings.py - Configurações finais
EMAIL_SUBJECT_PREFIX = '[Sistema de Agenda] '

# Para produção, considere adicionar:
DEFAULT_FROM_EMAIL = 'Sistema de Agenda <andernet@gmail.com>'
SERVER_EMAIL = 'erros@sistemaagenda.com'

# Headers para melhor organização no Gmail
EMAIL_EXTRA_HEADERS = {
    'X-Priority': '1',
    'Importance': 'High',
    'X-Mailer': 'Django SMTP',
}

# Produção - Configurações Gmail Corrigidas
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False  # IMPORTANTE: TLS e SSL são mutuamente exclusivos
EMAIL_HOST_USER = 'andernet@gmail.com'
EMAIL_HOST_PASSWORD = 'ktdu sqae najt thmj'
DEFAULT_FROM_EMAIL = 'andernet@gmail.com'  # Deve ser o mesmo que EMAIL_HOST_USER
SERVER_EMAIL = 'andernet@gmail.com'

# Configurações adicionais importantes
EMAIL_TIMEOUT = 30  # Timeout em segundos




# Configurações adicionais de CSRF (opcionais)
CSRF_COOKIE_SECURE = False  # True em produção com HTTPS
CSRF_COOKIE_HTTPONLY = False
CSRF_USE_SESSIONS = False
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'  # View padrão

# Se estiver usando subdomínios ou domínios diferentes
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    # Adicione outros domínios se necessário
]

# # Cookie settings
# CSRF_COOKIE_NAME = 'csrftoken'
# CSRF_COOKIE_AGE = 31449600  # 1 ano em segundos
# CSRF_COOKIE_PATH = '/'
# CSRF_COOKIE_DOMAIN = None
# CSRF_COOKIE_SAMESITE = 'Lax'



# # settings.py - Adicionar logging detalhado
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'level': 'DEBUG',
#             'class': 'logging.StreamHandler',
#         },
#         'file': {
#             'level': 'DEBUG',
#             'class': 'logging.FileHandler',
#             'filename': 'debug.log',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['console', 'file'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#         'login': {
#             'handlers': ['console', 'file'],
#             'level': 'DEBUG',
#             'propagate': False,
#         },
#     },
# }