# Generated by Django 5.2.1 on 2025-09-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_aluno', models.CharField(max_length=100, verbose_name='Nome do aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dias', models.CharField(max_length=20, verbose_name='Dias')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_escola', models.CharField(max_length=100, verbose_name='Nome da escola')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True, verbose_name='Conteúdo Ministrado')),
                ('start_time', models.DateField(blank=True, null=True, verbose_name='Data da conteúdo ministrado')),
                ('dever', models.TextField(blank=True, null=True, verbose_name='Dever de casa')),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Data da entrega')),
                ('data_postagem', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_livro', models.CharField(max_length=100, verbose_name='Nome do livro')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_materia', models.CharField(max_length=100, verbose_name='Nome da matéria')),
            ],
        ),
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ordem', models.CharField(max_length=20, verbose_name='Ordem do horário')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_professor', models.CharField(max_length=100, verbose_name='Nome do Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('turma', models.CharField(max_length=100, verbose_name='Nome da turma')),
            ],
        ),
    ]
