# Generated by Django 5.2.1 on 2025-09-18 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alunos',
            name='fk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_user', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='escola',
            name='responsaveis',
            field=models.ManyToManyField(blank=True, related_name='escolas_responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alunos',
            name='fk_escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_escola', to='cal.escola', verbose_name='Escola'),
        ),
        migrations.AddField(
            model_name='event',
            name='fk_escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dever_escola', to='cal.escola', verbose_name='Escola'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='fk_dias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_semana', to='cal.dias', verbose_name='Dias da semana'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='fk_escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_escola', to='cal.escola', verbose_name='Escola'),
        ),
        migrations.AddField(
            model_name='livro',
            name='fk_escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='livro_escola', to='cal.escola', verbose_name='Nome da escola'),
        ),
        migrations.AddField(
            model_name='event',
            name='fk_livro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dever_livro', to='cal.livro', verbose_name='Livro'),
        ),
        migrations.AddField(
            model_name='livro',
            name='fk_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livro_materia', to='cal.materia', verbose_name='Matéria'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='fk_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_materia', to='cal.materia', verbose_name='Matéria'),
        ),
        migrations.AddField(
            model_name='event',
            name='fk_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dever_materia', to='cal.materia', verbose_name='Matéria'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='fk_ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_ordem', to='cal.ordem', verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='professor',
            name='fk_escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores_escola', to='cal.escola', verbose_name='Nome da escola'),
        ),
        migrations.AddField(
            model_name='professor',
            name='fk_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_materias', to='cal.materia', verbose_name='Matéria'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='fk_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_professor', to='cal.professor', verbose_name='Professor'),
        ),
        migrations.AddField(
            model_name='event',
            name='fk_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dever_professor', to='cal.professor', verbose_name='Professor'),
        ),
        migrations.AddField(
            model_name='turma',
            name='fk_escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turma_escola', to='cal.escola', verbose_name='Nome da escola'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='fk_turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_turma', to='cal.turma', verbose_name='Turma'),
        ),
        migrations.AddField(
            model_name='event',
            name='fk_turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dever_turma', to='cal.turma', verbose_name='Turma'),
        ),
        migrations.AddField(
            model_name='alunos',
            name='fk_turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_turma', to='cal.turma', verbose_name='Turma'),
        ),
    ]
