# Generated by Django 5.2.6 on 2025-09-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dias',
            name='ordem',
            field=models.IntegerField(default=0, verbose_name='Ordem'),
        ),
    ]
